<?php defined('BASEPATH') or exit('No direct script access allowed'); ?>
<h1>Resuscytacja krążeniowo-oddechowa</h1>
Zobaczyłeś leżącego na ulicy mężczyznę. Co robisz? Uciekasz, pomagasz, a może nie wiesz co zrobić? Ten materiał przybliży Ci podstawowe zasady udzielania pierwszej pomocy podczas nagłego zatrzymania krążenia. 1.Zadbaj o swoje bezpieczeń stwo! Zaczynając udzielać pierwszej pomocy musisz zadbać o swoje bezpieczeń stwo. Przechodząc przez drogę zobaczy czy nie przejeżdża samochód który mógłby Cię potrącić. Usuń  rozbite szkło znajdujące się obok osoby poszkodowanej, po prostu udzielając pomocy osobom poszkodowanym, Ty masz być bezpieczny. FOTO BEZPIECZEŃ STWO/ROZGLĄDANIE SIĘ2.Sprawdź czy poszkodowany reaguje! Podejdź do poszkodowanego i zapytaj: „Czy Pan mnie słyszy?”. Jeśli nie usłyszysz odpowiedzi podejdź bliżej i zadaj jeszcze raz pytanie potrząsając poszkodowanego za ramiona FOTO SPRAWDZENIE ŚWIADOMOŚCI3.Udrożnienie dróg oddechowych!/Wsparcie psychiczne! a)Poszkodowany reaguje: Jeśli osobie poszkodowanej nie zagraża niebezpieczeń stwo zostaw ją w pozycji, w której go zastałeś. Bądź przy rannym, zapewnij mu wsparcie psychiczne. Dowiedz się jak najwięcej o jego aktualnym stanie: czy coś go boli, czy choruje (np. nadciśnienie, cukrzyca, itd.), jak się czuje. Jeśli będziesz potrzebował pomocy, wezwij ją– nie bój się zadzwonić na numer 112/999. Mając informacje o stanie zdrowia poszkodowanego dyspozytor pokieruje Cię co masz robić dalej oraz jeśli będzie taka potrzeba wyśle Zespół Ratownictwa Medycznego. Regularnie oceniaj stan osoby poszkodowanej FOTO OPIEKA NAD POSZKODOWANYM b)Poszkodowany nie reaguje: Zawołaj o pomoc. Przeważnie gdy się odwrócisz wokół Ciebie będzie tłum ludzi obserwujących co się dzieje. Wskaż konkretną osobęktóra Ci pomoże np. „Pan w czarnej kurtce – proszę mi pomóc”. Istnieje duże ryzyko że jeśli tego nie zrobisz, tłum rozejdzie się lub będzie udawałże Cięnie słyszy, dlatego musisz wskazać konkretną osobę. Następnym krokiem jest udrożnienie dróg oddechowych. Odwróć poszkodowanego tak, by leżałna plecach, a następnie udrożnij jego drogi oddechowe odginając głowę oraz unosząc żuchwę: Umieść jedną rękę na czole poszkodowanego, zaś palce drugiej ręki połóżnażuchwie poszkodowanego. Odchyl głowę oraz unieśżuchwę w celu udrożnienia dróg oddechowych.
FOTO UDROŻNIENIE DRÓG ODDECHOWYCH 4.Sprawdzenie oddechu! Utrzymując drożnośćdróg oddechowych sprawdź czy poszkodowany oddycha. Wykonując tączęśćprocedury RKO zawsze wykorzystuj trzy zmysły: wzrok, słuch i dotyk. Oceń  wzrokiem czy klatka piersiowa poszkodowanego się rusza, jednocześnie nasłuchuj przy ustach osoby poszkodowanej szmerów oddechowych oraz postaraj się wyczuć ruch powietrza na swoim policzku. Na sprawdzenie oddechu nie przeznaczaj więcej niż 10 sekund. Jeśli masz wątpliwości czy poszkodowany oddycha policz ile oddechów w ciągu 10 sekund było prawidłowych ( nie licząc słabych oddechów czy teżwestchnięć). Jeśli mniej niż 2 oddechy na 10 sekund przyjmij że poszkodowany oddycha nieprawidłowo, zaśjeśli dalej nie masz pewności ile oddechów było prawidłowych, postępuj tak jakby oddech był nieprawidłowy.  FOTO SPRAWDZENIE ODDECHU 5.Uciskanie klatki piersiowej!/Pozycja boczna ustalona! a)Jeżeli oddech jest prawidłowy Ułóż poszkodowanego w pozycji bocznej (bezpiecznej). Wykonaj następujące czynności: Jeśli poszkodowany nosi okulary – zdejmij je Jeśli poszkodowany ma na sobie np. koszulę– rozluźnij kołnierzyk Upewnij się czy poszkodowany leży na plecach i ma wyprostowane obie nogi Bliższą tobie rękę poszkodowanego ułóż pod kątem prostym w stosunku do ciała poszkodowanego, a następnie zegnij w łokciu tak, by dłoń  ręki była skierowana do góryFOTO POZYCJA BOCZNA I Złap za dalsząkoń czynę dolną poszkodowanego na wysokości kolana i zegnij nogęw kolanie nie odrywając stopy poszkodowanego od podłoża FOTO POZYCJA BOCZNA II Złap dalszą rękę poszkodowanego tak, aby palce dłoni poszkodowanego przeplatały sięz palcami dłoni ratownika – Ciebie. FOTO POZYCJA BOCZNA III Przełóż splecioną rękę poszkodowanego tak, by dłoń  znajdowała się przy bliższym Tobie policzku poszkodowanego.  Podtrzymując rękę przy policzku, pociągnij drugą ręką za kolano poszkodowanego tak, aby poszkodowany obróciłsię na bok w twoim kierunku.
FOTO POZYCJA BOCZNA IV Odchyl głowę poszkodowanego do tyłu, aby poprawić drożnośćdróg oddechowych Wezwij pomoc lub poproś kogoś by wezwał pomoc – przekaż tej osobie informacje o poszkodowanym. Regularnie oceniaj oddech poszkodowanego gdyżmoże on zaniknąć, a wtedy musisz prowadzić dalsze czynności ratunkowe. FOTO WEZWANIE POMOCY b)Jeżeli oddech jest nieprawidłowy CDN: http://ratownik-med.pl/index.php/ratownictwo-mainmenu-34/rko-doroli-bls-mainmenu-55.html XDXDXDXD :P
<form class="finish_kurs_form" action="" method="post">
	<input type="hidden" name="kurs_id" value="1">
	<input type="submit" value="Zakończ kurs 1">
</form>
